name: First Workflow
on: [push]

jobs: 
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo string
              run: echo "hello World"
            - name: run multiline command
              run: |
                npm -v
                node -v

